- data/data_generator.rb
- test/graphemetest.c
- test/normtest.c
- test/tests.h
- utf8proc.c
- utf8proc.h
- utf8proc_data.c
I was seeing the define for `ssize_t` cause some collisions and compilation errors in Julia (with MSVC) due to libuv also using this type. I think a typedef would be preferable? Could potentially use `intptr_t` for this instead, but I'm not sure exactly which versions of MSVC would support that.
> Use a typedef instead of a #define for ssize_t with MSVC

- .gitignore
- Makefile
- test/charwidth.c
- test/graphemetest.c
- test/iterate.c
- test/tests.h
- test/valid.c
- utf8proc.c
- utf8proc.h
This change also improves the performance of the functions utf8proc_iterate and utf8proc_codepoint_valid, and fixes surrogate handling in utf8proc_encode_char.
> Fix #34 handle 66 Unicode non-characters and surrogates correctly

- .gitignore
- Makefile
- test/case.c
- utf8proc.c
- utf8proc.h
Other than tests, this is a trivial patch to expose `tolower` and `toupper` replacements via a documented C API.
This will make it easy to fix JuliaLang/julia#11471.
> add toupper/tolower functions

- Makefile
* Allow optimization flgas in CFLAGS to be overwritten
* Use Uppercase CC and CFLAGS
* Create all soname symlinks
Signed-off-by: Justin Lecher <jlec@gentoo.org>
> Enhance build process

- Makefile
> Always pass -fPIC in CFLAGS

- Makefile
- test/tests.h
- utf8proc.c
This commit removes a spurious external symbol for the internal function `unsafe_encode_char()`, which I noticed while preparing a package of the utf8proc library for Debian.
> Do not export internal unsafe_encode_char()

- appveyor.yml
> Fix MingW build test

- .gitignore
- .travis.yml
- MANIFEST
- Makefile
- data/Makefile
- data/charwidths.jl
- test/charwidth.c
- test/iterate.c
- test/printproperty.c
- test/tests.c
- test/tests.h
This commit series fixes several build warnings, and ensures that `make clean` reverts the build tree to a pristine state. This is the last pull request in an effort to bring utf8proc into shape for distribution packaging, specifically for Debian.
> Fix build warnings

- CMakeLists.txt
- MANIFEST
- Makefile
- NEWS.md
It would be nice if you could tie a ribbon around #55, #56, #57, #58 by tagging a patch release. A tagged version makes it much easier to package utf8proc for Debian, which is a prerequisite for getting Julia 0.4.0 into Debian. I updated NEWS with all user-visible changes.
> Version 1.3.1

- CMakeLists.txt
- MANIFEST
- Makefile
- test/iterate.c
- utf8proc.c
It went undetected so far because the corresponding test program was reusing the same initialized
memory buffer several times.
> Fix overrun

- .travis.yml
certificate is expired on cache.e.ip.saba.us, it now lives at cache.julialang.org
> fix the travis cache

- data/Makefile
This ensures the tests keep working when a new Unicode version is released.
> Use versioned Unicode data URLs

- .travis.yml
After the warning (#70) has been fixed, please merge to ensure warnings will never go unnoticed again.
```
cc -O2 -fPIC -std=c99 -Wall -Wmissing-prototypes -pedantic -DUTF8PROC_EXPORTS -c -o utf8proc.o utf8proc.c
utf8proc.c: In function ‘grapheme_break_extended’:
utf8proc.c:287:7: warning: variable ‘lbc_override’ set but not used [-Wunused-but-set-variable]
int lbc_override = lbc;
^
```
> Convert compiler warnings to errors for Travis builds

- .travis.yml
- Makefile
since MSVC doesn't understand this flag, and the current
mechanism for building Julia with MSVC goes through the makefile
as suggested by @petercolberg at https://github.com/JuliaLang/utf8proc/pull/55#discussion_r71060437
> Move -Wmissing-prototypes from Makefile to .travis.yml

- bench/bench.c
and declare it ahead of time to avoid "error: 'for' loop initial declarations are only allowed in C99 mode"
> use a different variable name for nested loop in bench.c

- utf8proc.h
Change UINT16_MAX from `~(utf8proc_uint16_t)0` to fixed value `65535U` to prevent weird behaviour in complex expressions like in #82.
> Change UINT16_MAX macro to 65535U

- CMakeLists.txt
- MANIFEST
- Makefile
- NEWS.md
- test/custom.c
- utf8proc.c
- utf8proc.h
This PR supplies two new functions, `utf8proc_map_custom` and `utf8proc_decompose_custom`, which are like the old `utf8proc_map` and `utf8proc_decompose` except that they allow the user to pass a custom mapping function that is applied to every codepoint in the input before any other transformation is performed.
This will allow us to fix #11 without adding any Julia-specific code into utf8proc, and seems like a generally useful mechanism to have.
cc @jiahao, @StefanKarpinski
> new utf8proc_map_custom for hooking in user-defined custom mappings

- data/Makefile
Ref: https://github.com/JuliaLang/julia/pull/19725, UnicodeData.txt is now being cached in JuliaLang/julia's build. cc @tkelman
> Don't use cached version of UnicodeData.txt

- utf8proc.c
> Fix declaration-after-statement warning when compiling in strict C90 mode.

- Makefile
This PR makes the Makefile use `$(LDFLAGS)` when building libutf8proc.dylib, just as it already does when building libutf8proc.so.
> Use LDFLAGS when building libutf8proc.dylib

- CMakeLists.txt
utf8proc's use of `add_definitions` affects the global definitions.
Instead, use `target_compile_definitions`.
> [CMake] Use target_compile_definitions to avoid affecting global definitions

- CMakeLists.txt
- Add install target so that one can `nmake install` it in a specified `CMAKE_INSTALL_PREFIX`
- Suffix static library with '_static' in case the compiler is `MSVC`. Useful for packaging both shared and static libraries in Windows in a single tarball.
> Enhance CMakeLists.txt

- MANIFEST
- Makefile
- libutf8proc.pc.in
This adds a pkg-config file for libutf8proc.
Fixes issue https://github.com/JuliaStrings/utf8proc/issues/105.
> Generate and install a pkg-config file.

- CMakeLists.txt
Rebased PR by @per-gron (closes #65).
> rebased cmake updates

- Makefile
- data/Makefile
- test/misc.c
- utf8proc.c
- utf8proc.h
> add utf8proc_unicode_version

- CMakeLists.txt
In some cases (such as using the library via `add_subdirectory` in CMake), it may be desirable to disable installation.
> [CMake] Add UTF8PROC_NO_INSTALL option

- Makefile
Several options passed to $(CC) are not portable, e.g., for HP aCC.
Move them to variables.
As discussed in #153.
> Improve portability of Make

- appveyor.yml
This reverts commit 7e834d77024d770875559d853b09b8bb7f9321a1.
Hopefully these now work again after 11bb3d9dc796bb006c79c2962a7d19abcadfb3df and #188
Closes #186, if this was the source of the problem as suggested in https://github.com/JuliaStrings/utf8proc/pull/178#issuecomment-605615456
> Revert "disable tests under mingw"

- CMakeLists.txt
The cmake file expects the parent folder to be named "utf8proc",
otherwise the target_include_directories won't work, as it references
an unknown path.
This deviates from the install targets (both cmake and makefile) in
putting the include file into a subfolder in contrast to the top level
folder. This also prevents using the library with the recent cmake
addition of FetchContent.
This change unifies the include file handling by using the local path
for cmake as well.
This might break existing uses. As a workaround, we could add a dummy
include file in the old location (new utf8proc subfolder). I'm not sure
if that is necessary.
> Unify include file handling

- utf8proc.h
There is a small typo in utf8proc.h.
Should read `encountered` rather than `encounted`.
> docs: fix simple typo, encounted -> encountered

- test/graphemetest.c
- utf8proc.c
Fixes #203. JuliaLang/julia#37680 will also be fixed once Julia updates utf8proc.
Replaces #204.
> Fix grapheme breaks on string-initial

- Makefile
- test/case.c
- test/graphemetest.c
- test/iterate.c
- test/printproperty.c
- test/tests.c
- utf8proc.c
Added explicit casts or changed variable types to remove Sign-Conversion warnings from utf8proc.c
Turned on Sign-Conversion warnings in Makefile
Changes to tests will be coming in a separate PR
> Fix Sign-Conversion warnings in library and test code

- .github/workflows/cmake.yml
- .github/workflows/make.yml
Build on: ubuntu, windows, macOS, win+mingw64
Fix #206
We can add more combinations if needed, for example: ubuntu+mingw64, win+cygwin, *+clang.
Results of CI run: https://github.com/inkydragon/utf8proc/actions/runs/1324116342
> [ci] set github CI

- test/fuzzer.c
This fixes a timeout issue on OSS-Fuzz (~130KB input taking more than 30 seconds).
> Limit input length for fuzzer

- Makefile
`llvm-ar` warns when the archive does not exist and `c` is not passed.
> Add c flag when invoking ar

- CMakeLists.txt
- MANIFEST
- Makefile
- NEWS.md
- utf8proc.h
we can tag a new release once this is merged
note that the ABI version changed to 3.0 since the `utf8proc_property_t` struct definition changed, breaking ABI compatibility (albeit only for code that directly accesses this struct).
> version 2.9 bump

- CMakeLists.txt
This will silence the following warning:
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
> upgrade minimum cmake version

- utf8proc.h
This improves support for targeting wasm32 with clang 12, and I don't think anything else in inttypes.h is used that isn't already in stdint.h.
> Use stdint.h instead of inttypes.h

- CMakeLists.txt
Minimum version is 3.5 and policy CMP0048 was introduced in 3.0, meaning
that it will always be set to `NEW`.
> build: remove unnecessary policy check

- .github/workflows/make.yml
Otherwise the job fails with the error message
"/bin/sh: julia: command not found"
> ci(macos): install julia dependency

- .github/dependabot.yml
This will prevent CI failing from using deprecated actions.
> ci: add dependabot to update actions

- test/fuzzer.c
As a result, the number of covered lines increased by 10%
> fuzz: improve code coverage

- CMakeLists.txt
This is to prevent the following warning:
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.10 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
> Update minimum cmake version to 3.10

- data/data_generator.jl
- utf8proc.c
- utf8proc_data.c
Fixes the warnings introduced by #277, and noted here: https://github.com/JuliaStrings/utf8proc/issues/280#issuecomment-2566676370
cc @eschnett 
(I don't recall why `int32_t` is used for characters, rather than unsigned; maybe `-1` is used as a sentinel somewhere?   Or maybe it's because `wchar_t` is often signed on Unix systems where it is 32 bits? In any case, it's safe, since the maximum codepoint is only `10FFFF`.)
> silence warnings: use int32_t for chars more consistently

- CMakeLists.txt
- MANIFEST
- Makefile
- NEWS.md
- utf8proc.h
Closes #280.  Closes #272.
~~Requires #282 first.~~
> prepare for 2.10 release
